#!/bin/bash

set -e
exec > >(tee /var/log/user-data.log | logger -t user-data -s 2>/dev/console) 2>&1

dnf update -y
dnf install -y docker docker-compose-plugin

systemctl enable docker
systemctl start docker
sleep 8

mkdir -p /opt/wordpress
cd /opt/wordpress

cat <<'EOF' > docker-compose.yml
version: "3.8"

services:
  wordpress:
    image: wordpress:php8.4-apache
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: mazin
      WORDPRESS_DB_PASSWORD: wppassword
      WORDPRESS_DB_NAME: wordpress
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: mysqladminpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: mazin
      MYSQL_PASSWORD: wppassword
    volumes:
      - mysql_storage:/var/lib/mysql

volumes:
  mysql_storage:
EOF

docker compose up -d
docker ps